#ugabuga
name: Build and Analyze with SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build  # Assicura che questo job si esegua solo dopo il successo del job build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Migliora l'analisi della rilevanza

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn clean install

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
            -Dsonar.organization=my_organization
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.LOGIN }}
